### ISSUE TITLE
Cool project

### ISSUE THREAD

**Issue by fantasticsoul** [morewings/cra-template-quickstart-redux#141]
cra-template-quickstart-redux is cool project, would you like to try cra-template-concent-ts?
https://github.com/concentjs/cra-template-concent-ts

here is the online demo:
https://codesandbox.io/s/cra-template-concent-ts-2x347

**Comment by morewings** [comment]
Oh, @fantasticsoul, you tried to promote your library, but you didn't add a star on my repo. Shame.

**Comment by fantasticsoul** [comment]
I have add a star on your repo
